const data = [
  {
    id: 1,
    name: "Andriaus Vaisiai, UAB",
    city: "Vilnius",
    categories: ["fruits", "vegetables"],
    img: "./images/fruits1.png",
  },
  {
    id: 2,
    name: "Kebabai 123, UAB",
    city: "Kaunas",
    categories: ["fast_food"],
    img: "./images/fast_food1.png",
  },
  {
    id: 3,
    name: "Citrinu Pasaulis, UAB",
    city: "Klaipeda",
    categories: ["fruits", "vegetables"],
    img: "./images/fruits2.png",
  },
  {
    id: 4,
    name: "Dainiaus Darzoves, UAB",
    city: "Vilnius",
    categories: ["vegetables"],
    img: "./images/fruits3.png",
  },
  {
    id: 5,
    name: "Skanus Kebabai, UAB",
    city: "Kaunas",
    categories: ["fast_food"],
    img: "./images/fast_food2.png",
  },
  {
    id: 6,
    name: "Vaisiniai sapnai, MB",
    city: "Klaipeda",
    categories: ["vegetables"],
    img: "./images/fruits4.png",
  },
  {
    id: 7,
    name: "Sauletekis, UAB",
    city: "Vilnius",
    categories: ["vegetables"],
    img: "./images/fruits5.png",
  },
  {
    id: 8,
    name: "Bistro, UAB",
    city: "Kaunas",
    categories: ["fast_food", "fruits"],
    img: "./images/fast_food3.png",
  },
  {
    id: 9,
    name: "UZkandis, MB",
    city: "Kaunas",
    categories: ["fast_food", "vegetables"],
    img: "./images/fast_food4.png",
  },
  {
    id: 10,
    name: "Valgyk kiek telpa, MB",
    city: "Klaipeda",
    categories: ["fast_food"],
    img: "./images/fast_food5.png",
  },
  {
    id: 11,
    name: "Pienas, UAB",
    city: "Vilnius",
    categories: ["desserts"],
    img: "./images/dessert1.png",
  },
  {
    id: 12,
    name: "Saldainiai, UAB",
    city: "Kaunas",
    categories: ["desserts"],
    img: "./images/dessert2.png",
  },
  {
    id: 13,
    name: "Rimti skoniai, UAB",
    city: "Klaipeda",
    categories: ["desserts"],
    img: "./images/dessert3.png",
  },
  {
    id: 14,
    name: "Desertine, UAB",
    city: "Vilnius",
    categories: ["desserts"],
    img: "./images/dessert4.png",
  },
  {
    id: 15,
    name: "Penkios po keturiu, UAB",
    city: "Kaunas",
    categories: ["desserts"],
    img: "./images/dessert5.png",
  },
  {
    id: 16,
    name: "Makaronu fabrikas, UAB",
    city: "Klaipeda",
    categories: ["pasta", "vegetables"],
    img: "./images/pasta1.png",
  },
  {
    id: 17,
    name: "Draugo uzeiga, UAB",
    city: "Vilnius",
    categories: ["pasta", "fast_food"],
    img: "./images/pasta2.png",
  },
  {
    id: 18,
    name: "Sveikas maistas, UAB",
    city: "Kaunas",
    categories: ["pasta", "vegetables"],
    img: "./images/pasta3.png",
  },
  {
    id: 19,
    name: "Picelinas, UAB",
    city: "Klaipeda",
    categories: ["pasta", "fast_food"],
    img: "./images/pasta4.png",
  },
  {
    id: 20,
    name: "Pica, UAB",
    city: "Vilnius",
    categories: ["pasta", "desserts"],
    img: "./images/pasta5.png",
  },
];

export default data;
